baseURL = 'https://connor.klipsch.net/'
locale = 'en-us'
title = 'Connor Klipsch'
theme = 'risotto-fork'
author = 'Connor Klipsch'
languageCode = 'en'
DefaultContentLanguage = "en"


disableKinds = ["RSS"]

sectionPagesMenu = "main"

[pagination]
pagerSize = 3

[menu]
    [[menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume/resume"
        weight = 10
    [[menu.main]]
        identifier = "attribution"
        name = "Attribution"
        url = "/attribution/attribution/"
        weight = 10